version: "Build {build}"

environment:
  matrix:
    - PHP_VERSION: '7.1'
      PHP_ARCHITECTURE: x86
      PREFER_LOWEST: 
    - PHP_VERSION: '7.2'
      PHP_ARCHITECTURE: x64
      PREFER_LOWEST: 

matrix:
  fast_finish: true

clone_depth: 50

cache:
  - C:\tools\downloads -> .appveyor\configure.ps1
  - '%ProgramFiles%\WindowsPowerShell\Modules\VcRedist -> .appveyor\configure.ps1'
  - '%LOCALAPPDATA%\Composer\files'

services:
  - mysql

init:
  - set PATH=C:\Program Files\MySQL\MySQL Server 5.7\bin;%PATH%
  - set MYSQL_PWD=Password12!
  - nuget install redis-64 -excludeversion -OutputDirectory ../redis
  - ..\redis\redis-64\tools\redis-server.exe --service-install --service-name redis1 --port 6379 --requirepass "randomredis"
  - ..\redis\redis-64\tools\redis-server.exe --service-start --service-name redis1
  - ..\redis\redis-64\tools\redis-server.exe --service-install --service-name redis2 --port 6380 --requirepass "randomredis"
  - ..\redis\redis-64\tools\redis-server.exe --service-start --service-name redis2

install:
  - ps: .\.appveyor\configure.ps1
  - composer install --no-progress --no-suggest --optimize-autoloader --no-ansi --no-interaction %PREFER_LOWEST%

build: off

test_script:
  - mysql --user=root -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY '';" || exit 0
  - mysql --user=root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost' WITH GRANT OPTION; FLUSH PRIVILEGES;"
  - cd /d "%APPVEYOR_BUILD_FOLDER%"
  - set APPVEYOR_SAVE_CACHE_ON_ERROR=true
  - composer test

deploy: off
