# Global/default configuration
dist: trusty
language: php
sudo: false
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - build/node_modules
notifications:
  email: false

# Job list
matrix:
  fast_finish: true
  allow_failures:
    - name: Test with PHP nightly
  include:

    - name: Test UI with PHP 7.2
      php: '7.2'
      before_script:
        - ./.travis/setup-apache.sh
        - ./.travis/composer-deps.sh
      addons:
        hosts:
        - concrete5-test.test
        chrome: stable
      script:
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://concrete5-test.test
        - codecept build
        - codecept run
