# Global/default configuration
dist: trusty
language: php
sudo: false
cache:
  npm: true
  directories:
    - $HOME/.composer/cache
    - build/node_modules
notifications:
  email: false
env:
  - REDIS_VERSION=redis-4.3.0

# Job list
matrix:
  fast_finish: true
  allow_failures:
    - name: Test with PHP nightly
    - name: Test with PHP 7.4
  include:

    - name: Test with PHP 7.1 (with code coverage)
      php: '7.1'
      before_script:
        - wget --tries=5 https://scrutinizer-ci.com/ocular.phar
        - ./.travis/composer-deps.sh
        - ./.travis/setup-redis.sh
      script:
        - php test.php
        - phpdbg -qrr ./concrete/vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover
      after_script:
        - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

    - name: Check PHP coding style
      php: '7.1'
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer phpcs

    - name: Check JS coding style
      language: node_js
      node_js: '10'
      before_script:
        - ./.travis/setup-build.sh
      script:
        - pushd build && grunt js:check && popd

    - name: Rebuild JS assets
      language: node_js
      node_js: '10'
      before_script:
        - ./.travis/setup-build.sh
      script:
        - ./.travis/rebuild-assets.sh

    - name: Test with PHP 5.5
      php: '5.5'
      before_script:
        - ./.travis/composer-deps.sh
        - ./.travis/setup-redis.sh
      script:
        - php test.php
        - composer test
      env:
        - REDIS_VERSION=redis-4.3.0

    - name: Test with PHP 5.6
      php: '5.6'
      before_script:
        - ./.travis/composer-deps.sh
        - ./.travis/setup-redis.sh
      script:
        - composer test
      env:
        - REDIS_VERSION=redis-4.3.0

    - name: Test with PHP 7.0
      php: '7.0'
      before_script:
        - ./.travis/composer-deps.sh
        - ./.travis/setup-redis.sh
      script:
        - composer test

    - name: Test with PHP 7.1 (lowest composer dependencies)
      php: '7.1'
      before_script:
        - COMPOSER_FLAGS='--prefer-lowest' ./.travis/composer-deps.sh
        - ./.travis/setup-redis.sh
      script:
        - composer test

    - name: Test with PHP 7.2
      php: '7.2'
      before_script:
        - ./.travis/composer-deps.sh
        - ./.travis/setup-redis.sh
      script:
        - composer test

    - name: Test with PHP 7.3
      php: '7.3'
      before_script:
        - ./.travis/composer-deps.sh
        - ./.travis/setup-redis.sh
      script:
        - composer test

    - name: Test with PHP 7.4
      php: 7.4snapshot
      before_script:
        - ./.travis/composer-deps.sh
        - ./.travis/setup-redis.sh
      script:
        - composer test

    - name: Test with PHP nightly
      php: nightly
      before_script:
        - ./.travis/composer-deps.sh
        - ./.travis/setup-redis.sh
      script:
        - composer test
