# Global/default configuration
dist: trusty
language: php
sudo: false
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - build/node_modules
notifications:
  email: false

# Job list
matrix:
  fast_finish: true
  allow_failures:
    - name: Test with PHP nightly
  include:

    - name: Test UI with PHP 7.2
      php: '7.2'
      before_install:
        - "sudo ./.travis/setup-apache.sh"
        - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
      before_script:
        - ./.travis/composer-deps.sh
        - ./.travis/setup-chrome.sh
      addons:
        hosts:
        - concrete5-test.test
        chrome: stable
      script:
        #         - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9515 http://concrete5-test.test
        - concrete/vendor/codeception/codeception/codecept build
        - concrete/vendor/codeception/codeception/codecept run
