# Global/default configuration
dist: trusty
language: php
sudo: false
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - build/node_modules
notifications:
  email: false

# Job list
matrix:
  fast_finish: true
  allow_failures:
    - name: Test with PHP nightly
  include:

    - name: Test with PHP 7.1 (with code coverage)
      php: '7.1'
      before_script:
        - wget --tries=5 https://scrutinizer-ci.com/ocular.phar
        - ./.travis/composer-deps.sh
      script:
        - phpdbg -qrr ./concrete/vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover
      after_script:
        - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

    - name: Check PHP coding style
      php: '7.1'
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer phpcs

    - name: Check JS coding style
      language: node_js
      node_js: '10'
      before_script:
        - ./.travis/setup-build.sh
      script:
        - pushd build && grunt js:check && popd

    - name: Rebuild JS assets
      language: node_js
      node_js: '10'
      before_script:
        - ./.travis/setup-build.sh
      script:
        - ./.travis/rebuild-assets.sh

    - name: Test with PHP 5.5
      php: '5.5'
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer test

    - name: Test with PHP 5.6
      php: '5.6'
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer test

    - name: Test with PHP 7.0
      php: '7.0'
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer test

    - name: Test with PHP 7.1 (lowest composer dependencies)
      php: '7.1'
      before_script:
        - COMPOSER_FLAGS='--prefer-lowest' ./.travis/composer-deps.sh
      script:
        - composer test

    - name: Test with PHP 7.2
      php: '7.2'
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer test

    - name: Test with PHP 7.3
      php: '7.3'
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer test

    - name: Test with PHP nightly
      php: nightly
      before_script:
        - ./.travis/composer-deps.sh
      script:
        - composer test

    - name: Test UI with PHP 7.2
      php: '7.2'
      before_install:
        - "sudo ./.travis/setup-apache.sh"
      before_script:
        - ./.travis/composer-deps.sh
        - ./.travis/setup-chrome.sh
      addons:
        hosts:
        - concrete5-test.test
        chrome: stable
      script:
        - ./chromedriver --url-base=wd/hub --whitelisted-ips=  > /dev/null 2>&1&
        - concrete/vendor/codeception/codeception/codecept build
        - concrete/vendor/codeception/codeception/codecept run -vvv || true
        - cat tests/UI/_output/Concrete.UITests.Page.AddCest.loadNewPage.fail.html || true
