# Global/default configuration
dist: trusty
language: php
sudo: false
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - build/node_modules
notifications:
  email: false

# Job list
matrix:
  fast_finish: true
  allow_failures:
    - name: Test with PHP nightly
  include:

    - name: Test UI with PHP 7.2
      php: '7.2'
      before_install:
        - "sudo ./.travis/setup-apache.sh"
      before_script:
        - ./.travis/composer-deps.sh
        - ./.travis/setup-chrome.sh
      addons:
        hosts:
        - concrete5-test.test
        chrome: stable
      script:
        - ./chromedriver --url-base=wd/hub --whitelisted-ips=  > /dev/null 2>&1&
        - concrete/vendor/codeception/codeception/codecept build
        - concrete/vendor/codeception/codeception/codecept run
